# Generated by Django 4.1.7 on 2023-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("activity", models.TextField(max_length=1000)),
                ("starting_time", models.DateTimeField()),
                ("reminder_time", models.DateTimeField()),
            ],
        ),
    ]
