# Generated by Django 4.1.7 on 2023-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("Done", "D"), ("Un attempted", "U")],
                default="un attempted",
                max_length=15,
            ),
        ),
    ]
