steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/poetic-set-386615/gcr.io/poetic-set-386615/benkyeyune/django-app:v0'
      - '.'
      - '-f'
      - './to_do_app/Dockerfile'  # Update the path to the Dockerfile

    dir: 'to_do_app'  # Set the Docker build context to the root of your project directory
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/poetic-set-386615/gcr.io/poetic-set-386615/benkyeyune/django-app:v0'
  
  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'django-app'
      - '--image'
      - 'gcr.io/poetic-set-386615/gcr.io/poetic-set-386615/benkyeyune/django-app:v0'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west6'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      # Add more flags if needed, such as --allow-unauthenticated
  
  # Step 4: (Optional) Run database migrations or other setup tasks
  # Replace the command with your specific setup tasks
  - name: 'gcr.io/poetic-set-386615/gcr.io/poetic-set-386615/benkyeyune/django-app:v0'
    args:
      - 'python'
      - 'manage.py'
      - 'migrate'
  
timeout: '1600s'  # Set a longer timeout if needed
