
 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/poetic-set-386615/django-app:$COMMIT_SHA', '.','-f','./to_do_app/Dockerfile']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/poetic-set-386615/django-app:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'django-app'
   - '--image'
   - 'gcr.io/poetic-set-386615/django-app:$COMMIT_SHA'
   - '--region'
   - 'europe-west6'
   - '--allow-unauthenticated'
 images:
 - 'gcr.io/poetic-set-386615/django-app:$COMMIT_SHA'